# Generated by Django 4.2.7 on 2025-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_share_systems',
            field=models.BooleanField(default=False, help_text='Bu kullanıcının sistem paylaşımı yapabilmesine izin ver', verbose_name='Sistem Paylaşım Yetkisi'),
        ),
    ]
