# Generated by Django 5.1.5 on 2025-05-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keychain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crediental',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crediental',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keychain.crediental'),
        ),
        migrations.AddField(
            model_name='crediental',
            name='users',
            field=models.ManyToManyField(related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crediental',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keychain.project'),
        ),
        migrations.AlterUniqueTogether(
            name='crediental',
            unique_together={('code', 'project')},
        ),
    ]
