# Generated by Django 4.2.19 on 2025-05-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='keychain.project'),
        ),
    ]
