# Generated by Django 4.2.19 on 2025-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0004_company_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='system_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
