# Generated by Django 4.2.19 on 2025-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0005_project_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
