# Generated by Django 4.2.7 on 2025-06-29 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keychain', '0008_systemshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='keychain.project'),
        ),
        migrations.AlterField(
            model_name='crediental',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crediental',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keychain.crediental'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_systems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemshare',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='keychain.company'),
        ),
    ]
