# Generated by Django 4.2.7 on 2025-06-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keychain', '0008_systemshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='keychain.project'),
        ),
        migrations.AlterField(
            model_name='crediental',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crediental',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='keychain.crediental'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_systems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemshare',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='keychain.company'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('activity_description', models.TextField(verbose_name='Faaliyet Açıklaması')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Süre (saat)')),
                ('is_billable', models.CharField(choices=[('yes', 'Evet'), ('no', 'Hayır')], default='yes', max_length=3, verbose_name='Faturlanabilirlik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_activities', to=settings.AUTH_USER_MODEL)),
                ('primary_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_activities', to=settings.AUTH_USER_MODEL, verbose_name='Kişi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='keychain.project')),
                ('secondary_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_activities', to=settings.AUTH_USER_MODEL, verbose_name='İkincil Kişi')),
            ],
            options={
                'verbose_name': 'Faaliyet',
                'verbose_name_plural': 'Faaliyetler',
                'ordering': ['-created_date'],
            },
        ),
    ]
