# Generated by Django 4.2.7 on 2025-06-26 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0009_alter_company_owner_alter_company_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_date', '-created_date'], 'verbose_name': 'Faaliyet', 'verbose_name_plural': 'Faaliyetler'},
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default=datetime.date.today, help_text='Faaliyetin gerçekleştiği tarih', verbose_name='Faaliyet Tarihi'),
        ),
    ]
