# Generated by Django 4.2.7 on 2025-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, help_text='Faaliyetle ilgili dosya, resim veya PDF yükleyebilirsiniz', null=True, upload_to='activity_files/%Y/%m/', verbose_name='Dosya'),
        ),
    ]
