# Generated by Django 4.2.19 on 2025-07-10 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keychain', '0011_activity_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Faaliyetle ilgili dosya, resim veya PDF yükleyebilirsiniz', upload_to='activity_files/%Y/%m/', verbose_name='Dosya')),
                ('original_name', models.CharField(help_text='Dosyanın yüklendiği andaki orijinal adı', max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='keychain.activity', verbose_name='Faaliyet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Faaliyet Dosyası',
                'verbose_name_plural': 'Faaliyet Dosyaları',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
