# Generated by Django 4.2.19 on 2025-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0012_remove_activity_attachment_activityattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityattachment',
            name='original_name',
            field=models.CharField(db_column='original_filename', help_text='Dosyanın yüklendiği andaki orijinal adı', max_length=255, verbose_name='Orijinal Dosya Adı'),
        ),
    ]
