# Generated by Django 4.2.19 on 2025-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0013_alter_activityattachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.TextField(verbose_name='Faaliyet'),
        ),
    ]
