# Generated by Django 4.2.19 on 2025-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keychain', '0014_alter_activity_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
